# Site settings
author: Lyndel Evan Barnes
title: 
header-img: img/home-bg.png
email: l.evan.barnes@gmail.com
copyright_name: Lyndel Evan Barnes
description: > # this means to ignore newlines until "baseurl:"
  
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  lindenmeadow

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
